hostname : "socket.gethostname()"
mac_address : "uuid.getnode()"
ACCESS_TOKEN : "{hostname}-{mac_address}"
# -------------------------------
SERVER_IP : "vivernd.com"
TCP_PORT : 5050
UDP_PORT : 5051
MQTT_PORT : 1883
MOSQUITTO_PORT : 1888
IMAGE_PORT : 5052
PYSSH_PORT : 8980
BUFFER_SIZE : 65535
SEND_IMAGES : False
ROSBOARD_SOCKET : "tcp"
SEND_FREQ : 10  # hz
CONNECTION_TIMEOUT : 60  # sec


